#!/usr/bin/env sh

source $(dirname $0)/util/base.sh

TS_NODE_PATH=$(npm_which "ts-node")
KARMA_PATH=$(npm_which "karma")

echo_run $TS_NODE_PATH -P $ROOT_DIR/config/tsconfig.node.json $KARMA_PATH start $ROOT_DIR/config/karma.conf.ts --config --single-run --reporters mocha

