#!/usr/bin/env sh

source $(dirname $0)/util/base.sh

TSLINT_PATH=$(npm_which "tslint")

$TSLINT_PATH --config "$CONFIG_DIR/tslint.json" --format prose --type-check --project "$CONFIG_DIR/tsconfig.tslint.json"

