#!/usr/bin/env sh

source $(dirname $0)/util/base.sh

ONCHANGE_PATH=$(npm_which "onchange")
WEBPACK_DEV_SERVER_PATH=$(npm_which "webpack-dev-server")
SERVE_COMMAND="$WEBPACK_DEV_SERVER_PATH --config $CONFIG_DIR/webpack.devserver.ts"

export TS_NODE_PROJECT="$ROOT_DIR/config/tsconfig.node.json"
$ONCHANGE_PATH $ALL_TYPESCRIPT_SOURCE_FILES $ALL_CONFIG_FILES --initial --wait --verbose --poll 100 -- $SERVE_COMMAND

