#!/usr/bin/env sh

source $(dirname $0)/util/base.sh

ONCHANGE_PATH=$(npm_which "onchange")
SINGLE_RUN_SCRIPT="$SCRIPTS_DIR/test"

echo_run $ONCHANGE_PATH "$TEST_DIR/**/*.ts" "$TEST_DIR/**/*.tsx" "$SOURCE_DIR/**/*.ts" "$SOURCE_DIR/**/*.tsx" "$CONFIG_DIR/**/*" "$SINGLE_RUN_SCRIPT" --initial --wait --verbose -- $SINGLE_RUN_SCRIPT
