#!/usr/bin/env sh

source $(dirname $0)/util/base.sh

CONCURRENTLY_PATH=$(npm_which "concurrently")

$CONCURRENTLY_PATH --success all --prefix "[{name}]" --prefix-colors magenta,cyan --names client-test-watch,server-test-watch "$SCRIPTS_DIR/client-test-watch" "$SCRIPTS_DIR/server-test-watch"

