#!/usr/bin/env sh

source $(dirname $0)/util/base.sh

ONCHANGE_PATH=$(npm_which "onchange")

SINGLE_RUN_SCRIPT="$SCRIPTS_DIR/test"

$ONCHANGE_PATH $ALL_TYPESCRIPT_TEST_FILES $ALL_TYPESCRIPT_SOURCE_FILES $ALL_CONFIG_FILES $SINGLE_RUN_SCRIPT --initial --wait --verbose --poll 100 -- $SINGLE_RUN_SCRIPT

